# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('article_image', models.ImageField(upload_to='articles/')),
                ('category', models.ManyToManyField(to='gall.Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gall.Location')),
            ],
        ),
    ]
