# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(to='gall.Category'),
        ),
    ]
